### ISSUE TITLE
Vehicle Operators

### ISSUE THREAD

**Issue by gabviana** [google/cfr#21]
Hi,

I was trying to get this demo running on my local. I had two problems when you click on Upload from CSV:
**1.** The third bullet option "Vehicle Operators" doesn't show up on this example;
**2.** The .csv samples that you gave us for the shipments (_shipmentsSample.csv_) and vehicles (_vehiclesSample.csv_) give me an error on **step 4 "Geocode and Validate**" that says: _Error validating file: Cannot read properties of null (reading 'error')_

Inside the code there's no error that can explains what happening.
Is there anyone with the same problem?

Thanks in advanced.
Regards,
Gabriela

**Comment by jasonmccollumwoolpert** [comment]
Hi Gabriela,

Access to Vehicle Operators requires setting the `allow_experimental_features` value in your `local.auto.tfvars` file to "true". See the Optional Parameters section in the [deployment docs](https://github.com/google/cfr/blob/main/docs/deployment.md#optional-variables) for more info. Also note that you'll need to have your project allowlisted by Google to actually use experimental API features, this just unlocks the related features in the app.

Second issue looks to be related to an errant extra line in `vehiclesSample.csv`. Fix is incoming, but in the meantime you can open the CSV in a plain text editor and just remove the empty line at the end of the file and it should load correctly.
