### ISSUE TITLE
Do not display breaks outside of vehicle [start, end].

### ISSUE THREAD

**Issue by stevengaygoogle** [google/cfr#56]
Vehicle breaks do not count towards costs if they are before vehicle start or after vehicle end.
The schedule part of the interface still displays them in those cases, and also display wait time between the vehicle time window and the "outside" break.

Instead, there should be no waiting time displayed, and outside breaks should either no be displayed or displayed suggesting the break is not performed, for instance in grey.

**Comment by jasonmccollumwoolpert** [comment]
Thanks, opening up a PR to address. Is this functionality documented somewhere? Would be helpful to make it clear why these scheduled breaks are different.

**Comment by stevengaygoogle** [comment]
It is not very explicit in the documentation: https://cloud.google.com/optimization/docs/reference/rpc/google.cloud.optimization.v1#breakrule
But breaks that before vehicle start time or after vehicle end time do not affect the solution, they can be ignored.

Thanks for your work! I use the interface a lot to visualize the effects of tweaks to routing models, it's extremely useful!
