### ISSUE TITLE
Routing client for dart?

### ISSUE THREAD

**Issue by dev-akshat** [google/cfr#7]
Is there a cloud fleet grouting client for dart to use Optimization API.

We want to use Optimization API for a flutter app. After going through documentation it's not clear how to do it. 

Is there some client similar to Java and Python client for this API?
[Client Docs](https://cloud.google.com/optimization/docs/optimize_tours_client_libraries)

**Comment by chrisheecho** [comment]
Thanks @dev-akshat , let me see what we can do and come back to you soon

**Comment by chrisheecho** [comment]
@dev-akshat Dart is a [Google API Client Library and NOT a Cloud Cilent LIbrary](https://cloud.google.com/apis/docs/client-libraries-explained#cloud-client-libraries)

Google API Client Libraries have the following limitations per the website
- Provide access to the API's REST interface only; gRPC is not supported.
- Have autogenerated interface code that might not be as idiomatic as the Cloud Client Libraries.
- Handle all the low-level details of communication with the server, including [authenticating with Google](https://cloud.google.com/docs/authentication).
- Can be installed using familiar package management tools such as npm and pip.

Are you still ok with these limitations?

**Comment by chrisheecho** [comment]
Wondering if you have any updates here if no response in a day or two, will close this item

**Comment by chrisheecho** [comment]
closing since there is no repsonse over a week
