### ISSUE TITLE
Metrics per Route grid sort behavior issue

### ISSUE THREAD

**Issue by hollemawoolpert** [google/cfr#82]
1. Generate solution
2. Go to Metadata view, Metrics per Route
3. Sort by Traveled time

Expected: travel time would be sorted by hour/minute
Actual: travel times below two hours are sorted incorrectly. Example below shows sorting treating 01:35 as greater than 22:37.

<img width="1252" alt="image" src="https://github.com/google/cfr/assets/54112955/ea630015-c04f-46b0-902a-074145930ca5">

**Comment by hollemawoolpert** [comment]
I cannot reproduce in a scenario where max traveled time is sub 20 hours.

**Comment by jasonmccollumwoolpert** [comment]
After some testing, issue seems to be that durations greater than 24 hours are truncated to only the hours and seconds components.
