### ISSUE TITLE
Created a service account...

### ISSUE THREAD

**Issue by MikeAtNavagis** [google/cfr#9]
The readme for local development says "a service account was created in the project setup", but it was not

Here is the location of the text:
https://github.com/google/cfr/blob/main/docs/development.md#service-account-credentials

Here is a link to the referenced project setup:
https://github.com/google/cfr/blob/main/docs/project.md

**Comment by morabitowoolpert** [comment]
@MikeAtNavagis We updated the development docs. They no longer assume project setup and/or deployment have been run, and include minimal setup steps for projects without an app deployment.
